services:
  postgres:
    image: postgres:16.6
    container_name: postgre-sql_cardSearch
    env_file:
      - ./env/postgres.env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend_cardSearch
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend_cardSearch
    ports:
      - "3003:80"
    links:
      - backend
  
volumes:
  postgresdata:

